version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: sharepoint-connector-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sharepoint-network

  sharepoint-connector:
    build: .
    container_name: sharepoint-connector-app
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sharepoint-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  sharepoint-network:
    driver: bridge